[book]
authors = ["Russia9"]
language = "en"
multilingual = false
src = "src"
title = "DevOps Notes"

[output.html]
git-repository-url = "https://github.com/Russia9/notes"
edit-url-template = "https://github.com/Russia9/notes/{path}"
